trigger:
- master

resources:
- repo: self

variables:
  dockerRegistryServiceConnection: '6aea47e3-718c-4025-b8e2-f1e139c20d7c'
  imageRepository: 'app1/app1nginx'
  containerRegistry: 'asdevopsacr.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: Default   # ✅ THIS IS THE FIX
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
